//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETDomaci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ispit
    {
        public int indeks { get; set; }
        public int id_predmeta { get; set; }
        public short godina_roka { get; set; }
        public string oznaka_roka { get; set; }
        public short ocena { get; set; }
        public Nullable<System.DateTime> datum_ispita { get; set; }
        public Nullable<short> bodovi { get; set; }
    
        public virtual dosije dosije { get; set; }
        public virtual ispitni_rok ispitni_rok { get; set; }
        public virtual predmet predmet { get; set; }
    }
}
