//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GETDomaci.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mstudEntities1 : DbContext
    {
        public mstudEntities1()
            : base("name=mstudEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dosije> dosijes { get; set; }
        public virtual DbSet<ispit> ispits { get; set; }
        public virtual DbSet<ispitni_rok> ispitni_rok { get; set; }
        public virtual DbSet<predmet> predmets { get; set; }
    }
}
